// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcVVhcl_6MmLdCUhHtf9il5jwS0sWJvJc',
    appId: '1:659623248782:web:fa60cd8a18213792f15adf',
    messagingSenderId: '659623248782',
    projectId: 'pharmasage-432af',
    authDomain: 'pharmasage-432af.firebaseapp.com',
    storageBucket: 'pharmasage-432af.appspot.com',
    measurementId: 'G-JRBE5PZ6WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx-l5v4BmFS-yKSioy8JxqY8aci_XmOW4',
    appId: '1:659623248782:android:6060586fda88ab4af15adf',
    messagingSenderId: '659623248782',
    projectId: 'pharmasage-432af',
    storageBucket: 'pharmasage-432af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmO9ES5eqJKVjJCv3otWM7_gyRX0e4hFc',
    appId: '1:659623248782:ios:62313f59872dd91af15adf',
    messagingSenderId: '659623248782',
    projectId: 'pharmasage-432af',
    storageBucket: 'pharmasage-432af.appspot.com',
    iosBundleId: 'com.example.pharmasage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmO9ES5eqJKVjJCv3otWM7_gyRX0e4hFc',
    appId: '1:659623248782:ios:7d56ae2efa272c0bf15adf',
    messagingSenderId: '659623248782',
    projectId: 'pharmasage-432af',
    storageBucket: 'pharmasage-432af.appspot.com',
    iosBundleId: 'com.example.pharmasage.RunnerTests',
  );
}
